

hlp = [...
'  Command list:' 10 ...
'  ''E''	   : display currEnt temperatures for neutral and area 1 to 5 in 1/10 degrees' 10 ...
'  ''K''	   : get button 1&2 state ( CR+''00'' both released, CR+''11'' both pressed, CR+''10'' only button 1 pressed,...)' 10 ...
'  ''Q''	   : get error state ( return ''xxxxxx'', for each zone+neutral: ''x''=0:OK,''x''>1:ERROR )' 10 ...
'  ''Ur''	   : display temperature profile for each area: area number(1..5), profile enabled, number of points defined, points list' 10 ...
'  ''Uwxxxxxnnndddtttdddttt...'''' : User defined temperature profile, defined by segments of variable duration' 10 ...
'  			 ''xxxxx'': areas defined (''11111'' all areas, ''10000'' just area 1, ...), ''nnn'': number of segments (''000'' to ''999'')' 10 ...
'  			 ''dddttt'': list of duration of segment in ten of ms (''001'' to ''999'') and temperature at end of segment (''000'' to ''600'')' 10 ...
'  ''Uexxxxx'' : enable/disable temperature profile for each area (x=''1''=enable or ''0''=disable=default)' 10 ...
]


lf = find(hlp == 10);

command_re = '\n[ \t]*''[A-Z][a-z]*\.*[ \t]*''';
begs = regexp(hlp,command_re) + 1;


for b = begs
    e = lf(lf > b);
    e = e(1);
    str = hlp(b:e);
    quotes = find(str == '''');
    cmd = str(quotes(1)+1:quotes(2)-1);
end


